assert_eq(mol.SPAWN_POS, {x = 0, y = 3, z = -8}, "stage2 spawn position")
assert_eq(mol.HOUSE_POS, {x = -6, y = 0, z = 0}, "house position constant")
assert_eq(mol.HOUSE_SIZE, {x = 12, y = 8, z = 10}, "house size constant")
assert_eq(mol.YARD_MIN, {x = -12, y = 0, z = -10}, "yard min constant")
assert_eq(mol.YARD_MAX, {x = 12, y = 0, z = 14}, "yard max constant")
assert_eq(mol.BOUNDARY_HEIGHT, 5, "boundary height constant")

assert_true(mol.BOUNDARY_HEIGHT > 1.25, "boundary exceeds jump height")
assert_true(not mol.is_yard_boundary_region({x = 0, y = 1, z = 0}), "inside yard not boundary region")
assert_true(mol.is_yard_boundary_region({x = -13, y = 1, z = 0}), "west outside boundary region")
assert_true(mol.is_yard_boundary_region({x = 13, y = 1, z = 0}), "east outside boundary region")
assert_true(mol.is_yard_boundary_region({x = 0, y = 1, z = -11}), "south outside boundary region")
assert_true(mol.is_yard_boundary_region({x = 0, y = 1, z = 15}), "north outside boundary region")
assert_true(not mol.is_yard_boundary_region({x = 13, y = 6, z = 0}), "outside above boundary height ignored")
